"""update column name

Revision ID: d23ecc60c33f
Revises: ae1ae5324663
Create Date: 2024-06-24 00:04:38.257691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23ecc60c33f'
down_revision = 'ae1ae5324663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_categorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profil_categorie', sa.String(length=120), nullable=True))
        batch_op.drop_column('profile_categorie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_categorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_categorie', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('profil_categorie')

    # ### end Alembic commands ###
